name: Print Date

on:
  push:
    branches:
      - master

jobs:
  ubuntu-date:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: print date
      run: date

  windows-date:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: print date
      run: "Get-Date"

  macos-date:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: print date
      run: date

  final-job:
    needs: [ubuntu-date,windows-date,macos-date]
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: print date
      run: date
